/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posconsole;

import java.awt.Event;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.PieChart.Data;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jovy
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Database dbconn = new Database();
    TimeCard tCard = new TimeCard();
    DefaultTableModel model = new DefaultTableModel();
    Object[][] menu = dbconn.LoadMenu();

    public GUI() {
        initComponents();
        new Thread() {
            public void run() {
                while (true) {                    
                    Date date = new Date();
                    /**
                     * Look at the console to see how to split the 
                     * date into pieces System.out.println(date);
                     */                                       
                    String[] time = date.toString().split(" ");                                        
                    lblRunningClock.setText(time[3] + " " + time[2]);                    
                }

            }
        }.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Background = new javax.swing.JPanel();
        Panel_TopButtons = new javax.swing.JPanel();
        btn_POS = new javax.swing.JButton();
        btn_Manager = new javax.swing.JButton();
        btn_TimeCard = new javax.swing.JButton();
        Panel_ParentCard = new javax.swing.JPanel();
        Card_POS = new javax.swing.JPanel();
        Card_Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_order = new javax.swing.JTable();
        Panel_PaymentButtons = new javax.swing.JPanel();
        btn_VoidItem = new javax.swing.JButton();
        btn_PrintBill = new javax.swing.JButton();
        btn_SaveBill = new javax.swing.JButton();
        btn_Pay = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_ClearAllItems = new javax.swing.JButton();
        Panel_ParentMenu = new javax.swing.JPanel();
        Panel_Drinks = new javax.swing.JPanel();
        btn_Coke = new javax.swing.JButton();
        btn_DietCoke = new javax.swing.JButton();
        btn_Sprite = new javax.swing.JButton();
        btn_Lemonade = new javax.swing.JButton();
        btn_SweetTea = new javax.swing.JButton();
        btn_Coffee = new javax.swing.JButton();
        Panel_Appetizers = new javax.swing.JPanel();
        btn_ChipsSalsa = new javax.swing.JButton();
        btn_Calamari = new javax.swing.JButton();
        btn_MozarellaSticks = new javax.swing.JButton();
        btn_FourWaySampler = new javax.swing.JButton();
        btn_SpinachArtiDip = new javax.swing.JButton();
        btn_SantaFeChkQue = new javax.swing.JButton();
        Panel_Burgers = new javax.swing.JPanel();
        btn_SouthWest = new javax.swing.JButton();
        btn_TheWorks = new javax.swing.JButton();
        btn_ThreeCheese = new javax.swing.JButton();
        btn_SwissMelt = new javax.swing.JButton();
        btn_BaconCheddar = new javax.swing.JButton();
        btn_CATCHBurger = new javax.swing.JButton();
        Panel_Wings = new javax.swing.JPanel();
        btn_OriginalWings = new javax.swing.JButton();
        btn_HotWingsNaked = new javax.swing.JButton();
        btn_LemonPepperWings = new javax.swing.JButton();
        btn_TeriyakiWings = new javax.swing.JButton();
        btn_HoneyBarbecueWings = new javax.swing.JButton();
        btn_CATCHWings = new javax.swing.JButton();
        Panel_Salad = new javax.swing.JPanel();
        btn_CeasarSalad = new javax.swing.JButton();
        btn_AsianSalad = new javax.swing.JButton();
        btn_GrilledSalmonSalad = new javax.swing.JButton();
        btn_ChickenAvocadoSalad = new javax.swing.JButton();
        btn_ChipotleSalad = new javax.swing.JButton();
        btn_RefreshingCATCHSalad = new javax.swing.JButton();
        Panel_Extras = new javax.swing.JPanel();
        btn_Fries = new javax.swing.JButton();
        btn_Coleslaw = new javax.swing.JButton();
        btn_MashedPotato = new javax.swing.JButton();
        btn_Corn = new javax.swing.JButton();
        btn_QuesoDip = new javax.swing.JButton();
        btn_PotatoWedges = new javax.swing.JButton();
        Panel_Dessert = new javax.swing.JPanel();
        btn_Chocolate_Mousse_Cheescake = new javax.swing.JButton();
        btn_RedVelvetCake = new javax.swing.JButton();
        btn_Cannoli = new javax.swing.JButton();
        btn_TiramisuCake = new javax.swing.JButton();
        btn_MilkShake = new javax.swing.JButton();
        btn_CATCHIceCreamSurprise = new javax.swing.JButton();
        Panel_Category = new javax.swing.JPanel();
        btn_Drinks = new javax.swing.JButton();
        btn_Appetizers = new javax.swing.JButton();
        btn_Burgers = new javax.swing.JButton();
        btn_Wings = new javax.swing.JButton();
        btn_Salads = new javax.swing.JButton();
        btn_Extras = new javax.swing.JButton();
        btn_Desserts = new javax.swing.JButton();
        Card_POSTable = new javax.swing.JPanel();
        Card_OrderPerTable = new javax.swing.JPanel();
        Card_Manager = new javax.swing.JPanel();
        Card_TimeCard = new javax.swing.JPanel();
        Card_EmpLogin = new javax.swing.JPanel();
        txt_empId = new javax.swing.JTextField();
        lbl_EmpLogin = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        Card_ClockinClockOut = new javax.swing.JPanel();
        btn_ClockInClockOut = new javax.swing.JButton();
        lbl_LoggedInAs = new javax.swing.JLabel();
        lbl_nameOfEmpLoggedIn = new javax.swing.JLabel();
        lblRunningClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Panel_Background.setBackground(new java.awt.Color(234, 253, 252));

        Panel_TopButtons.setBackground(new java.awt.Color(234, 253, 252));
        Panel_TopButtons.setLayout(new java.awt.GridBagLayout());

        btn_POS.setText("POS");
        btn_POS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_POSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 45, 25, 0);
        Panel_TopButtons.add(btn_POS, gridBagConstraints);

        btn_Manager.setText("Manager");
        btn_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManagerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 25, 0);
        Panel_TopButtons.add(btn_Manager, gridBagConstraints);

        btn_TimeCard.setText("Time Card");
        btn_TimeCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimeCardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 25, 0);
        Panel_TopButtons.add(btn_TimeCard, gridBagConstraints);

        Panel_ParentCard.setLayout(new java.awt.CardLayout());

        Card_POS.setBackground(new java.awt.Color(234, 253, 252));
        Card_POS.setLayout(new java.awt.CardLayout());

        Card_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "ITEM", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_order.setRowHeight(20);
        jScrollPane1.setViewportView(tbl_order);
        if (tbl_order.getColumnModel().getColumnCount() > 0) {
            tbl_order.getColumnModel().getColumn(0).setPreferredWidth(190);
            tbl_order.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        Card_Menu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 319, 374));

        Panel_PaymentButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_VoidItem.setBackground(new java.awt.Color(245, 41, 49));
        btn_VoidItem.setText("VOID ITEM");
        btn_VoidItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoidItemActionPerformed(evt);
            }
        });
        Panel_PaymentButtons.add(btn_VoidItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 57));

        btn_PrintBill.setBackground(new java.awt.Color(204, 204, 255));
        btn_PrintBill.setText("PRINT");
        Panel_PaymentButtons.add(btn_PrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 0, 91, 57));

        btn_SaveBill.setBackground(new java.awt.Color(255, 204, 204));
        btn_SaveBill.setText("SAVE");
        Panel_PaymentButtons.add(btn_SaveBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 120, 57));

        btn_Pay.setText("PAY");
        Panel_PaymentButtons.add(btn_Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, 57));

        btn_Cancel.setBackground(new java.awt.Color(204, 255, 204));
        btn_Cancel.setText("CANCEL");
        Panel_PaymentButtons.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 57));

        btn_ClearAllItems.setBackground(new java.awt.Color(153, 255, 153));
        btn_ClearAllItems.setText("CLEAR");
        btn_ClearAllItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearAllItemsActionPerformed(evt);
            }
        });
        Panel_PaymentButtons.add(btn_ClearAllItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 60, 90, 57));

        Card_Menu.add(Panel_PaymentButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 320, 120));

        Panel_ParentMenu.setLayout(new java.awt.CardLayout());

        btn_Coke.setText("Coke");
        btn_Coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CokeActionPerformed(evt);
            }
        });

        btn_DietCoke.setText("Diet Coke");
        btn_DietCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DietCokeActionPerformed(evt);
            }
        });

        btn_Sprite.setText("Sprite");
        btn_Sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SpriteActionPerformed(evt);
            }
        });

        btn_Lemonade.setText("Lemonade");
        btn_Lemonade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LemonadeActionPerformed(evt);
            }
        });

        btn_SweetTea.setText("Sweet Tea");
        btn_SweetTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SweetTeaActionPerformed(evt);
            }
        });

        btn_Coffee.setText("Coffee");
        btn_Coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CoffeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_DrinksLayout = new javax.swing.GroupLayout(Panel_Drinks);
        Panel_Drinks.setLayout(Panel_DrinksLayout);
        Panel_DrinksLayout.setHorizontalGroup(
            Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrinksLayout.createSequentialGroup()
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn_SweetTea)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Coffee))
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btn_Coke)
                        .addGap(5, 5, 5)
                        .addComponent(btn_DietCoke))
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Sprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Lemonade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_DrinksLayout.setVerticalGroup(
            Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrinksLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Coke)
                    .addComponent(btn_DietCoke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sprite)
                    .addComponent(btn_Lemonade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addComponent(btn_Coffee)
                        .addContainerGap())
                    .addComponent(btn_SweetTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Panel_ParentMenu.add(Panel_Drinks, "card9");

        btn_ChipsSalsa.setText("Chips & Salsa");
        btn_ChipsSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChipsSalsaActionPerformed(evt);
            }
        });

        btn_Calamari.setText("Calamari");
        btn_Calamari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalamariActionPerformed(evt);
            }
        });

        btn_MozarellaSticks.setText("Mozarella Sticks");
        btn_MozarellaSticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MozarellaSticksActionPerformed(evt);
            }
        });

        btn_FourWaySampler.setText("Four-Way Sampler");
        btn_FourWaySampler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FourWaySamplerActionPerformed(evt);
            }
        });

        btn_SpinachArtiDip.setText("Spinach Artichoke Dip");
        btn_SpinachArtiDip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SpinachArtiDipActionPerformed(evt);
            }
        });

        btn_SantaFeChkQue.setText("Santa Fe Artichoke Dip");
        btn_SantaFeChkQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SantaFeChkQueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_AppetizersLayout = new javax.swing.GroupLayout(Panel_Appetizers);
        Panel_Appetizers.setLayout(Panel_AppetizersLayout);
        Panel_AppetizersLayout.setHorizontalGroup(
            Panel_AppetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AppetizersLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btn_ChipsSalsa)
                .addGap(5, 5, 5)
                .addComponent(btn_Calamari)
                .addGap(5, 5, 5)
                .addComponent(btn_MozarellaSticks)
                .addGap(5, 5, 5)
                .addComponent(btn_FourWaySampler)
                .addGap(5, 5, 5)
                .addComponent(btn_SpinachArtiDip)
                .addGap(5, 5, 5)
                .addComponent(btn_SantaFeChkQue))
        );
        Panel_AppetizersLayout.setVerticalGroup(
            Panel_AppetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AppetizersLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Panel_AppetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ChipsSalsa)
                    .addComponent(btn_Calamari)
                    .addComponent(btn_MozarellaSticks)
                    .addComponent(btn_FourWaySampler)
                    .addComponent(btn_SpinachArtiDip)
                    .addComponent(btn_SantaFeChkQue)))
        );

        Panel_ParentMenu.add(Panel_Appetizers, "card9");

        btn_SouthWest.setText("SouthWest");
        btn_SouthWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SouthWestActionPerformed(evt);
            }
        });

        btn_TheWorks.setText("The Works");
        btn_TheWorks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TheWorksActionPerformed(evt);
            }
        });

        btn_ThreeCheese.setText("Three Cheese");
        btn_ThreeCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThreeCheeseActionPerformed(evt);
            }
        });

        btn_SwissMelt.setText("Swiss Melt");
        btn_SwissMelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SwissMeltActionPerformed(evt);
            }
        });

        btn_BaconCheddar.setText("Bacon Cheddar");
        btn_BaconCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BaconCheddarActionPerformed(evt);
            }
        });

        btn_CATCHBurger.setText("C.A.T.C.H. Burger");
        btn_CATCHBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CATCHBurgerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BurgersLayout = new javax.swing.GroupLayout(Panel_Burgers);
        Panel_Burgers.setLayout(Panel_BurgersLayout);
        Panel_BurgersLayout.setHorizontalGroup(
            Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BurgersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BurgersLayout.createSequentialGroup()
                        .addComponent(btn_SouthWest)
                        .addGap(2, 2, 2)
                        .addComponent(btn_TheWorks))
                    .addGroup(Panel_BurgersLayout.createSequentialGroup()
                        .addComponent(btn_SwissMelt)
                        .addGap(0, 0, 0)
                        .addComponent(btn_ThreeCheese))
                    .addGroup(Panel_BurgersLayout.createSequentialGroup()
                        .addComponent(btn_BaconCheddar)
                        .addGap(0, 0, 0)
                        .addComponent(btn_CATCHBurger)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        Panel_BurgersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_BaconCheddar, btn_CATCHBurger, btn_SouthWest, btn_SwissMelt, btn_TheWorks, btn_ThreeCheese});

        Panel_BurgersLayout.setVerticalGroup(
            Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BurgersLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SouthWest)
                    .addComponent(btn_TheWorks))
                .addGap(1, 1, 1)
                .addGroup(Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SwissMelt)
                    .addComponent(btn_ThreeCheese))
                .addGap(0, 0, 0)
                .addGroup(Panel_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_CATCHBurger, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_BaconCheddar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap())
        );

        Panel_BurgersLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_BaconCheddar, btn_CATCHBurger, btn_SouthWest, btn_SwissMelt, btn_TheWorks, btn_ThreeCheese});

        Panel_ParentMenu.add(Panel_Burgers, "card9");

        btn_OriginalWings.setText("Original");

        btn_HotWingsNaked.setText("Hot Wings Naked");

        btn_LemonPepperWings.setText("Lemon Pepper");

        btn_TeriyakiWings.setText("Teriyaki");

        btn_HoneyBarbecueWings.setText("Honey Barbecue");

        btn_CATCHWings.setText("C.A.T.C.H Wings");

        javax.swing.GroupLayout Panel_WingsLayout = new javax.swing.GroupLayout(Panel_Wings);
        Panel_Wings.setLayout(Panel_WingsLayout);
        Panel_WingsLayout.setHorizontalGroup(
            Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_WingsLayout.createSequentialGroup()
                .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_WingsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_OriginalWings)
                            .addComponent(btn_LemonPepperWings)))
                    .addGroup(Panel_WingsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_HoneyBarbecueWings)))
                .addGap(4, 4, 4)
                .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_WingsLayout.createSequentialGroup()
                        .addComponent(btn_CATCHWings)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_WingsLayout.createSequentialGroup()
                        .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_TeriyakiWings)
                            .addComponent(btn_HotWingsNaked))
                        .addContainerGap(167, Short.MAX_VALUE))))
        );

        Panel_WingsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_CATCHWings, btn_HoneyBarbecueWings, btn_HotWingsNaked, btn_LemonPepperWings, btn_OriginalWings, btn_TeriyakiWings});

        Panel_WingsLayout.setVerticalGroup(
            Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_WingsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_OriginalWings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HotWingsNaked))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LemonPepperWings)
                    .addComponent(btn_TeriyakiWings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_WingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_HoneyBarbecueWings)
                    .addComponent(btn_CATCHWings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        Panel_WingsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_CATCHWings, btn_HoneyBarbecueWings, btn_HotWingsNaked, btn_LemonPepperWings, btn_OriginalWings, btn_TeriyakiWings});

        Panel_ParentMenu.add(Panel_Wings, "card10");

        btn_CeasarSalad.setText("Ceasar Salad");

        btn_AsianSalad.setText("Asian Salad");

        btn_GrilledSalmonSalad.setText("Grilled Salmon");

        btn_ChickenAvocadoSalad.setText("Chicken Avocado Salad");

        btn_ChipotleSalad.setText("Chipotle Salad");

        btn_RefreshingCATCHSalad.setText("Refreshing C.A.T.C.H. Salad");

        javax.swing.GroupLayout Panel_SaladLayout = new javax.swing.GroupLayout(Panel_Salad);
        Panel_Salad.setLayout(Panel_SaladLayout);
        Panel_SaladLayout.setHorizontalGroup(
            Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SaladLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(Panel_SaladLayout.createSequentialGroup()
                        .addComponent(btn_ChickenAvocadoSalad)
                        .addGap(0, 0, 0)
                        .addComponent(btn_RefreshingCATCHSalad))
                    .addGroup(Panel_SaladLayout.createSequentialGroup()
                        .addComponent(btn_GrilledSalmonSalad)
                        .addGap(1, 1, 1)
                        .addComponent(btn_ChipotleSalad))
                    .addGroup(Panel_SaladLayout.createSequentialGroup()
                        .addComponent(btn_CeasarSalad)
                        .addGap(0, 0, 0)
                        .addComponent(btn_AsianSalad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_SaladLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_AsianSalad, btn_CeasarSalad, btn_ChickenAvocadoSalad, btn_ChipotleSalad, btn_GrilledSalmonSalad, btn_RefreshingCATCHSalad});

        Panel_SaladLayout.setVerticalGroup(
            Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SaladLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CeasarSalad)
                    .addComponent(btn_AsianSalad))
                .addGap(0, 0, 0)
                .addGroup(Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GrilledSalmonSalad)
                    .addComponent(btn_ChipotleSalad))
                .addGap(1, 1, 1)
                .addGroup(Panel_SaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RefreshingCATCHSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ChickenAvocadoSalad))
                .addContainerGap())
        );

        Panel_SaladLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_AsianSalad, btn_CeasarSalad, btn_ChickenAvocadoSalad, btn_ChipotleSalad, btn_GrilledSalmonSalad, btn_RefreshingCATCHSalad});

        Panel_ParentMenu.add(Panel_Salad, "card11");

        btn_Fries.setText("Fries");
        Panel_Extras.add(btn_Fries);

        btn_Coleslaw.setText("Coleslaw");
        Panel_Extras.add(btn_Coleslaw);

        btn_MashedPotato.setText("Mashed Potato");
        Panel_Extras.add(btn_MashedPotato);

        btn_Corn.setText("Corn");
        Panel_Extras.add(btn_Corn);

        btn_QuesoDip.setText("Queso Dip");
        Panel_Extras.add(btn_QuesoDip);

        btn_PotatoWedges.setText("Potato Wedges");
        Panel_Extras.add(btn_PotatoWedges);

        Panel_ParentMenu.add(Panel_Extras, "card12");

        btn_Chocolate_Mousse_Cheescake.setText("Chocolate Mousse Cheesecake");
        Panel_Dessert.add(btn_Chocolate_Mousse_Cheescake);

        btn_RedVelvetCake.setText("Red Velvet Cake");
        Panel_Dessert.add(btn_RedVelvetCake);

        btn_Cannoli.setText("Cannoli");
        Panel_Dessert.add(btn_Cannoli);

        btn_TiramisuCake.setText("Tiramisu Cake");
        Panel_Dessert.add(btn_TiramisuCake);

        btn_MilkShake.setText("Milkshake");
        Panel_Dessert.add(btn_MilkShake);

        btn_CATCHIceCreamSurprise.setText("C.A.T.C.H Ice Cream Surprise");
        Panel_Dessert.add(btn_CATCHIceCreamSurprise);

        Panel_ParentMenu.add(Panel_Dessert, "card13");

        Card_Menu.add(Panel_ParentMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 390, 490));

        btn_Drinks.setText("DRINKS");
        btn_Drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DrinksActionPerformed(evt);
            }
        });

        btn_Appetizers.setText("APPETIZERS");
        btn_Appetizers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AppetizersActionPerformed(evt);
            }
        });

        btn_Burgers.setText("BURGERS");
        btn_Burgers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BurgersActionPerformed(evt);
            }
        });

        btn_Wings.setText("WINGS");
        btn_Wings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WingsActionPerformed(evt);
            }
        });

        btn_Salads.setText("SALADS");
        btn_Salads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaladsActionPerformed(evt);
            }
        });

        btn_Extras.setText("EXTRAS");
        btn_Extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExtrasActionPerformed(evt);
            }
        });

        btn_Desserts.setText("DESSERT");
        btn_Desserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DessertsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_CategoryLayout = new javax.swing.GroupLayout(Panel_Category);
        Panel_Category.setLayout(Panel_CategoryLayout);
        Panel_CategoryLayout.setHorizontalGroup(
            Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CategoryLayout.createSequentialGroup()
                .addGroup(Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Extras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Salads, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Appetizers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Burgers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Wings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Drinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Desserts, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        Panel_CategoryLayout.setVerticalGroup(
            Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CategoryLayout.createSequentialGroup()
                .addComponent(btn_Drinks, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Appetizers, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Burgers, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(btn_Wings, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Salads, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Extras, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Desserts, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Card_Menu.add(Panel_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 190, 490));

        Card_POS.add(Card_Menu, "card3");

        Card_POSTable.setBackground(new java.awt.Color(234, 253, 252));
        Card_POSTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Card_OrderPerTableLayout = new javax.swing.GroupLayout(Card_OrderPerTable);
        Card_OrderPerTable.setLayout(Card_OrderPerTableLayout);
        Card_OrderPerTableLayout.setHorizontalGroup(
            Card_OrderPerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        Card_OrderPerTableLayout.setVerticalGroup(
            Card_OrderPerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        Card_POSTable.add(Card_OrderPerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 330, 490));

        Card_POS.add(Card_POSTable, "card2");

        Panel_ParentCard.add(Card_POS, "card2");

        Card_Manager.setBackground(new java.awt.Color(234, 253, 252));

        javax.swing.GroupLayout Card_ManagerLayout = new javax.swing.GroupLayout(Card_Manager);
        Card_Manager.setLayout(Card_ManagerLayout);
        Card_ManagerLayout.setHorizontalGroup(
            Card_ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Card_ManagerLayout.setVerticalGroup(
            Card_ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        Panel_ParentCard.add(Card_Manager, "card4");

        Card_TimeCard.setBackground(new java.awt.Color(234, 253, 252));
        Card_TimeCard.setLayout(new java.awt.CardLayout());

        lbl_EmpLogin.setText("Employee ID:");

        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Card_EmpLoginLayout = new javax.swing.GroupLayout(Card_EmpLogin);
        Card_EmpLogin.setLayout(Card_EmpLoginLayout);
        Card_EmpLoginLayout.setHorizontalGroup(
            Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card_EmpLoginLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(lbl_EmpLogin)
                .addGap(48, 48, 48)
                .addGroup(Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Login)
                    .addComponent(txt_empId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(370, 370, 370))
        );
        Card_EmpLoginLayout.setVerticalGroup(
            Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_EmpLoginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_empId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_EmpLogin))
                .addGap(30, 30, 30)
                .addComponent(btn_Login)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        Card_TimeCard.add(Card_EmpLogin, "card2");

        btn_ClockInClockOut.setText("Clock In / Clock Out");
        btn_ClockInClockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClockInClockOutActionPerformed(evt);
            }
        });

        lbl_LoggedInAs.setText("Logged in as:");

        lblRunningClock.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        lblRunningClock.setForeground(new java.awt.Color(255, 255, 255));
        lblRunningClock.setText("jLabel1");

        javax.swing.GroupLayout Card_ClockinClockOutLayout = new javax.swing.GroupLayout(Card_ClockinClockOut);
        Card_ClockinClockOut.setLayout(Card_ClockinClockOutLayout);
        Card_ClockinClockOutLayout.setHorizontalGroup(
            Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card_ClockinClockOutLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(btn_ClockInClockOut)
                .addGap(376, 376, 376))
            .addGroup(Card_ClockinClockOutLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRunningClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Card_ClockinClockOutLayout.createSequentialGroup()
                        .addComponent(lbl_LoggedInAs)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nameOfEmpLoggedIn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Card_ClockinClockOutLayout.setVerticalGroup(
            Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_ClockinClockOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunningClock)
                .addGap(139, 139, 139)
                .addGroup(Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LoggedInAs)
                    .addComponent(lbl_nameOfEmpLoggedIn))
                .addGap(47, 47, 47)
                .addComponent(btn_ClockInClockOut)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        Card_TimeCard.add(Card_ClockinClockOut, "card3");

        Panel_ParentCard.add(Card_TimeCard, "card5");

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_ParentCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(Panel_TopButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addComponent(Panel_TopButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_ParentCard, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_POSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_POSActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Menu);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_POSActionPerformed

    private void btn_TimeCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimeCardActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_TimeCard);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_TimeCardActionPerformed

    private void btn_VoidItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoidItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VoidItemActionPerformed

    private void btn_ClearAllItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearAllItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClearAllItemsActionPerformed

    private void btn_CokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CokeActionPerformed
        // TODO add your handling code here:
        /**
         * This is how you display an item and price from the database into a
         * DefaultTableModel
         */
        DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[0][0], menu[0][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_CokeActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:

        if (dbconn.isEmployee(Integer.parseInt(txt_empId.getText()))) {

            lbl_nameOfEmpLoggedIn.setText(dbconn.Login(Integer.parseInt(txt_empId.getText())));
            Panel_ParentCard.removeAll();
            Panel_ParentCard.add(Card_ClockinClockOut);
            Panel_ParentCard.repaint();
            Panel_ParentCard.revalidate();
        } else {
            JOptionPane.showMessageDialog(Card_EmpLogin, "Login Failed");
        }


    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_ClockInClockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClockInClockOutActionPerformed
        // TODO add your handling code here:
        tCard.setDate();

        dbconn.Clockin(Integer.parseInt(txt_empId.getText()), tCard.getDate().toString());
        System.out.println(txt_empId.getText() + "\n");
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Menu);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_ClockInClockOutActionPerformed

    private void btn_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManagerActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Manager);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_ManagerActionPerformed

    private void btn_SpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SpriteActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[2][0], menu[2][1]};
        model.addRow(row);

    }//GEN-LAST:event_btn_SpriteActionPerformed

    private void btn_SweetTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SweetTeaActionPerformed
          DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[4][0], menu[4][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_SweetTeaActionPerformed

    private void btn_AppetizersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AppetizersActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Appetizers);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_AppetizersActionPerformed

    private void btn_DrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DrinksActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Drinks);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_DrinksActionPerformed

    private void btn_BurgersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BurgersActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Burgers);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_BurgersActionPerformed

    private void btn_WingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WingsActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Wings);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_WingsActionPerformed

    private void btn_SaladsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaladsActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Salad);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_SaladsActionPerformed

    private void btn_ExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExtrasActionPerformed
        // TODO add your handling code here:
        Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Extras);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_ExtrasActionPerformed

    private void btn_DessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DessertsActionPerformed
        // TODO add your handling code here:
         Panel_ParentMenu.removeAll();
        Panel_ParentMenu.add(Panel_Dessert);
        Panel_ParentMenu.repaint();
        Panel_ParentMenu.revalidate();
    }//GEN-LAST:event_btn_DessertsActionPerformed

    private void btn_BaconCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BaconCheddarActionPerformed
DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[10][0], menu[10][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_BaconCheddarActionPerformed

    private void btn_DietCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DietCokeActionPerformed
    DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[1][0], menu[1][1]};
        model.addRow(row);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DietCokeActionPerformed

    private void btn_LemonadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LemonadeActionPerformed
           DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[3][0], menu[3][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_LemonadeActionPerformed

    private void btn_CoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CoffeeActionPerformed
           DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[5][0], menu[5][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_CoffeeActionPerformed

    private void btn_SouthWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SouthWestActionPerformed
     
    }//GEN-LAST:event_btn_SouthWestActionPerformed

    private void btn_TheWorksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TheWorksActionPerformed
     
    }//GEN-LAST:event_btn_TheWorksActionPerformed

    private void btn_SwissMeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SwissMeltActionPerformed

    }//GEN-LAST:event_btn_SwissMeltActionPerformed

    private void btn_ThreeCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThreeCheeseActionPerformed
     
    }//GEN-LAST:event_btn_ThreeCheeseActionPerformed

    private void btn_CATCHBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CATCHBurgerActionPerformed

    }//GEN-LAST:event_btn_CATCHBurgerActionPerformed

    private void btn_ChipsSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChipsSalsaActionPerformed
 DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[6][0], menu[6][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_ChipsSalsaActionPerformed

    private void btn_CalamariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalamariActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[7][0], menu[7][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_CalamariActionPerformed

    private void btn_MozarellaSticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MozarellaSticksActionPerformed
DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[8][0], menu[8][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_MozarellaSticksActionPerformed

    private void btn_FourWaySamplerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FourWaySamplerActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[9][0], menu[9][1]};
        model.addRow(row);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_FourWaySamplerActionPerformed

    private void btn_SpinachArtiDipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SpinachArtiDipActionPerformed
     DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[11][0], menu[11][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_SpinachArtiDipActionPerformed

    private void btn_SantaFeChkQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SantaFeChkQueActionPerformed
DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
        // Item and price
        Object[] row = {menu[12][0], menu[12][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_SantaFeChkQueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card_ClockinClockOut;
    private javax.swing.JPanel Card_EmpLogin;
    private javax.swing.JPanel Card_Manager;
    private javax.swing.JPanel Card_Menu;
    private javax.swing.JPanel Card_OrderPerTable;
    private javax.swing.JPanel Card_POS;
    private javax.swing.JPanel Card_POSTable;
    private javax.swing.JPanel Card_TimeCard;
    private javax.swing.JPanel Panel_Appetizers;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Burgers;
    private javax.swing.JPanel Panel_Category;
    private javax.swing.JPanel Panel_Dessert;
    private javax.swing.JPanel Panel_Drinks;
    private javax.swing.JPanel Panel_Extras;
    private javax.swing.JPanel Panel_ParentCard;
    private javax.swing.JPanel Panel_ParentMenu;
    private javax.swing.JPanel Panel_PaymentButtons;
    private javax.swing.JPanel Panel_Salad;
    private javax.swing.JPanel Panel_TopButtons;
    private javax.swing.JPanel Panel_Wings;
    private javax.swing.JButton btn_Appetizers;
    private javax.swing.JButton btn_AsianSalad;
    private javax.swing.JButton btn_BaconCheddar;
    private javax.swing.JButton btn_Burgers;
    private javax.swing.JButton btn_CATCHBurger;
    private javax.swing.JButton btn_CATCHIceCreamSurprise;
    private javax.swing.JButton btn_CATCHWings;
    private javax.swing.JButton btn_Calamari;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Cannoli;
    private javax.swing.JButton btn_CeasarSalad;
    private javax.swing.JButton btn_ChickenAvocadoSalad;
    private javax.swing.JButton btn_ChipotleSalad;
    private javax.swing.JButton btn_ChipsSalsa;
    private javax.swing.JButton btn_Chocolate_Mousse_Cheescake;
    private javax.swing.JButton btn_ClearAllItems;
    private javax.swing.JButton btn_ClockInClockOut;
    private javax.swing.JButton btn_Coffee;
    private javax.swing.JButton btn_Coke;
    private javax.swing.JButton btn_Coleslaw;
    private javax.swing.JButton btn_Corn;
    private javax.swing.JButton btn_Desserts;
    private javax.swing.JButton btn_DietCoke;
    private javax.swing.JButton btn_Drinks;
    private javax.swing.JButton btn_Extras;
    private javax.swing.JButton btn_FourWaySampler;
    private javax.swing.JButton btn_Fries;
    private javax.swing.JButton btn_GrilledSalmonSalad;
    private javax.swing.JButton btn_HoneyBarbecueWings;
    private javax.swing.JButton btn_HotWingsNaked;
    private javax.swing.JButton btn_LemonPepperWings;
    private javax.swing.JButton btn_Lemonade;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_Manager;
    private javax.swing.JButton btn_MashedPotato;
    private javax.swing.JButton btn_MilkShake;
    private javax.swing.JButton btn_MozarellaSticks;
    private javax.swing.JButton btn_OriginalWings;
    private javax.swing.JButton btn_POS;
    private javax.swing.JButton btn_Pay;
    private javax.swing.JButton btn_PotatoWedges;
    private javax.swing.JButton btn_PrintBill;
    private javax.swing.JButton btn_QuesoDip;
    private javax.swing.JButton btn_RedVelvetCake;
    private javax.swing.JButton btn_RefreshingCATCHSalad;
    private javax.swing.JButton btn_Salads;
    private javax.swing.JButton btn_SantaFeChkQue;
    private javax.swing.JButton btn_SaveBill;
    private javax.swing.JButton btn_SouthWest;
    private javax.swing.JButton btn_SpinachArtiDip;
    private javax.swing.JButton btn_Sprite;
    private javax.swing.JButton btn_SweetTea;
    private javax.swing.JButton btn_SwissMelt;
    private javax.swing.JButton btn_TeriyakiWings;
    private javax.swing.JButton btn_TheWorks;
    private javax.swing.JButton btn_ThreeCheese;
    private javax.swing.JButton btn_TimeCard;
    private javax.swing.JButton btn_TiramisuCake;
    private javax.swing.JButton btn_VoidItem;
    private javax.swing.JButton btn_Wings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRunningClock;
    private javax.swing.JLabel lbl_EmpLogin;
    private javax.swing.JLabel lbl_LoggedInAs;
    private javax.swing.JLabel lbl_nameOfEmpLoggedIn;
    private javax.swing.JTable tbl_order;
    private javax.swing.JTextField txt_empId;
    // End of variables declaration//GEN-END:variables
}
