/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posconsole;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jovy
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Database dbconn = new Database();
    TimeCard tCard = new TimeCard();
    DefaultTableModel model = new DefaultTableModel();
    Object[][] menu = dbconn.LoadMenu();

    public GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel_Background = new javax.swing.JPanel();
        Panel_TopButtons = new javax.swing.JPanel();
        btn_POS = new javax.swing.JButton();
        btn_Manager = new javax.swing.JButton();
        btn_TimeCard = new javax.swing.JButton();
        Panel_ParentCard = new javax.swing.JPanel();
        Card_POS = new javax.swing.JPanel();
        Card_Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_order = new javax.swing.JTable();
        Panel_PaymentButtons = new javax.swing.JPanel();
        btn_VoidItem = new javax.swing.JButton();
        btn_PrintBill = new javax.swing.JButton();
        btn_SaveBill = new javax.swing.JButton();
        btn_Pay = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_ClearAllItems = new javax.swing.JButton();
        Panel_ParentMenu = new javax.swing.JPanel();
        Panel_Drinks = new javax.swing.JPanel();
        btn_coke = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Panel_Appetizers = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        scr_Burgers = new javax.swing.JScrollPane();
        scr_Wings = new javax.swing.JScrollPane();
        scr_Salad = new javax.swing.JScrollPane();
        scr_Extras = new javax.swing.JScrollPane();
        scr_Desserts = new javax.swing.JScrollPane();
        Panel_Category = new javax.swing.JPanel();
        btn_Drinks = new javax.swing.JButton();
        btn_Appetizers = new javax.swing.JButton();
        btn_Burgers = new javax.swing.JButton();
        btn_Wings = new javax.swing.JButton();
        btn_Salads = new javax.swing.JButton();
        btn_Extras = new javax.swing.JButton();
        btn_Desserts = new javax.swing.JButton();
        Card_POSTable = new javax.swing.JPanel();
        Card_OrderPerTable = new javax.swing.JPanel();
        Card_Manager = new javax.swing.JPanel();
        Card_TimeCard = new javax.swing.JPanel();
        Card_EmpLogin = new javax.swing.JPanel();
        txt_empId = new javax.swing.JTextField();
        lbl_EmpLogin = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        Card_ClockinClockOut = new javax.swing.JPanel();
        btn_ClockInClockOut = new javax.swing.JButton();
        lbl_LoggedInAs = new javax.swing.JLabel();
        lbl_nameOfEmpLoggedIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Panel_Background.setBackground(new java.awt.Color(234, 253, 252));

        Panel_TopButtons.setBackground(new java.awt.Color(234, 253, 252));
        Panel_TopButtons.setLayout(new java.awt.GridBagLayout());

        btn_POS.setText("POS");
        btn_POS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_POSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 45, 25, 0);
        Panel_TopButtons.add(btn_POS, gridBagConstraints);

        btn_Manager.setText("Manager");
        btn_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManagerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 25, 0);
        Panel_TopButtons.add(btn_Manager, gridBagConstraints);

        btn_TimeCard.setText("Time Card");
        btn_TimeCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimeCardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 25, 0);
        Panel_TopButtons.add(btn_TimeCard, gridBagConstraints);

        Panel_ParentCard.setLayout(new java.awt.CardLayout());

        Card_POS.setBackground(new java.awt.Color(234, 253, 252));
        Card_POS.setLayout(new java.awt.CardLayout());

        Card_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "ITEM", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_order.setRowHeight(20);
        jScrollPane1.setViewportView(tbl_order);
        if (tbl_order.getColumnModel().getColumnCount() > 0) {
            tbl_order.getColumnModel().getColumn(0).setPreferredWidth(190);
            tbl_order.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        Card_Menu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 319, 374));

        Panel_PaymentButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_VoidItem.setBackground(new java.awt.Color(245, 41, 49));
        btn_VoidItem.setText("VOID ITEM");
        btn_VoidItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoidItemActionPerformed(evt);
            }
        });
        Panel_PaymentButtons.add(btn_VoidItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 57));

        btn_PrintBill.setBackground(new java.awt.Color(204, 204, 255));
        btn_PrintBill.setText("PRINT");
        Panel_PaymentButtons.add(btn_PrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 0, 91, 57));

        btn_SaveBill.setBackground(new java.awt.Color(255, 204, 204));
        btn_SaveBill.setText("SAVE");
        Panel_PaymentButtons.add(btn_SaveBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 120, 57));

        btn_Pay.setText("PAY");
        Panel_PaymentButtons.add(btn_Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, 57));

        btn_Cancel.setBackground(new java.awt.Color(204, 255, 204));
        btn_Cancel.setText("CANCEL");
        Panel_PaymentButtons.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 57));

        btn_ClearAllItems.setBackground(new java.awt.Color(153, 255, 153));
        btn_ClearAllItems.setText("CLEAR");
        btn_ClearAllItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearAllItemsActionPerformed(evt);
            }
        });
        Panel_PaymentButtons.add(btn_ClearAllItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 60, 90, 57));

        Card_Menu.add(Panel_PaymentButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 320, 120));

        Panel_ParentMenu.setLayout(new java.awt.CardLayout());

        btn_coke.setText("Coke");
        btn_coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cokeActionPerformed(evt);
            }
        });

        jButton7.setText("Diet Coke");

        jButton8.setText("Sprite");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Lemonade");

        jButton10.setText("Sweet Tea");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Coffee");

        javax.swing.GroupLayout Panel_DrinksLayout = new javax.swing.GroupLayout(Panel_Drinks);
        Panel_Drinks.setLayout(Panel_DrinksLayout);
        Panel_DrinksLayout.setHorizontalGroup(
            Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(Panel_DrinksLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)))
                .addGap(42, 42, 42))
        );

        Panel_DrinksLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_coke, jButton10, jButton11, jButton7, jButton8, jButton9});

        Panel_DrinksLayout.setVerticalGroup(
            Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_coke, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(Panel_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        Panel_DrinksLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_coke, jButton10, jButton11, jButton7, jButton8, jButton9});

        Panel_ParentMenu.add(Panel_Drinks, "card9");

        jButton12.setText("Chicken Tenders");

        javax.swing.GroupLayout Panel_AppetizersLayout = new javax.swing.GroupLayout(Panel_Appetizers);
        Panel_Appetizers.setLayout(Panel_AppetizersLayout);
        Panel_AppetizersLayout.setHorizontalGroup(
            Panel_AppetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AppetizersLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton12)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        Panel_AppetizersLayout.setVerticalGroup(
            Panel_AppetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AppetizersLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton12)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        Panel_ParentMenu.add(Panel_Appetizers, "card9");
        Panel_ParentMenu.add(scr_Burgers, "card4");
        Panel_ParentMenu.add(scr_Wings, "card5");
        Panel_ParentMenu.add(scr_Salad, "card6");
        Panel_ParentMenu.add(scr_Extras, "card7");
        Panel_ParentMenu.add(scr_Desserts, "card8");

        Card_Menu.add(Panel_ParentMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 390, 490));

        btn_Drinks.setText("DRINKS");

        btn_Appetizers.setText("APPETIZERS");

        btn_Burgers.setText("BURGERS");

        btn_Wings.setText("WINGS");

        btn_Salads.setText("SALADS");

        btn_Extras.setText("EXTRAS");

        btn_Desserts.setText("DESSERT");

        javax.swing.GroupLayout Panel_CategoryLayout = new javax.swing.GroupLayout(Panel_Category);
        Panel_Category.setLayout(Panel_CategoryLayout);
        Panel_CategoryLayout.setHorizontalGroup(
            Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CategoryLayout.createSequentialGroup()
                .addGroup(Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Extras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Salads, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Appetizers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Burgers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Wings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Drinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Desserts, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        Panel_CategoryLayout.setVerticalGroup(
            Panel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CategoryLayout.createSequentialGroup()
                .addComponent(btn_Drinks, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Appetizers, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Burgers, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(btn_Wings, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Salads, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Extras, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_Desserts, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Card_Menu.add(Panel_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 190, 490));

        Card_POS.add(Card_Menu, "card3");

        Card_POSTable.setBackground(new java.awt.Color(234, 253, 252));
        Card_POSTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Card_OrderPerTableLayout = new javax.swing.GroupLayout(Card_OrderPerTable);
        Card_OrderPerTable.setLayout(Card_OrderPerTableLayout);
        Card_OrderPerTableLayout.setHorizontalGroup(
            Card_OrderPerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        Card_OrderPerTableLayout.setVerticalGroup(
            Card_OrderPerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        Card_POSTable.add(Card_OrderPerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 330, 490));

        Card_POS.add(Card_POSTable, "card2");

        Panel_ParentCard.add(Card_POS, "card2");

        Card_Manager.setBackground(new java.awt.Color(234, 253, 252));

        javax.swing.GroupLayout Card_ManagerLayout = new javax.swing.GroupLayout(Card_Manager);
        Card_Manager.setLayout(Card_ManagerLayout);
        Card_ManagerLayout.setHorizontalGroup(
            Card_ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Card_ManagerLayout.setVerticalGroup(
            Card_ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        Panel_ParentCard.add(Card_Manager, "card4");

        Card_TimeCard.setBackground(new java.awt.Color(234, 253, 252));
        Card_TimeCard.setLayout(new java.awt.CardLayout());

        lbl_EmpLogin.setText("Employee ID:");

        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Card_EmpLoginLayout = new javax.swing.GroupLayout(Card_EmpLogin);
        Card_EmpLogin.setLayout(Card_EmpLoginLayout);
        Card_EmpLoginLayout.setHorizontalGroup(
            Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card_EmpLoginLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(lbl_EmpLogin)
                .addGap(48, 48, 48)
                .addGroup(Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Login)
                    .addComponent(txt_empId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(370, 370, 370))
        );
        Card_EmpLoginLayout.setVerticalGroup(
            Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_EmpLoginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(Card_EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_empId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_EmpLogin))
                .addGap(30, 30, 30)
                .addComponent(btn_Login)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        Card_TimeCard.add(Card_EmpLogin, "card2");

        btn_ClockInClockOut.setText("Clock In / Clock Out");
        btn_ClockInClockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClockInClockOutActionPerformed(evt);
            }
        });

        lbl_LoggedInAs.setText("Logged in as:");

        javax.swing.GroupLayout Card_ClockinClockOutLayout = new javax.swing.GroupLayout(Card_ClockinClockOut);
        Card_ClockinClockOut.setLayout(Card_ClockinClockOutLayout);
        Card_ClockinClockOutLayout.setHorizontalGroup(
            Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card_ClockinClockOutLayout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(btn_ClockInClockOut)
                .addGap(376, 376, 376))
            .addGroup(Card_ClockinClockOutLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lbl_LoggedInAs)
                .addGap(18, 18, 18)
                .addComponent(lbl_nameOfEmpLoggedIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Card_ClockinClockOutLayout.setVerticalGroup(
            Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_ClockinClockOutLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(Card_ClockinClockOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LoggedInAs)
                    .addComponent(lbl_nameOfEmpLoggedIn))
                .addGap(47, 47, 47)
                .addComponent(btn_ClockInClockOut)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        Card_TimeCard.add(Card_ClockinClockOut, "card3");

        Panel_ParentCard.add(Card_TimeCard, "card5");

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_ParentCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(Panel_TopButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addComponent(Panel_TopButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_ParentCard, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_POSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_POSActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Menu);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_POSActionPerformed

    private void btn_TimeCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimeCardActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_TimeCard);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_TimeCardActionPerformed

    private void btn_VoidItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoidItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VoidItemActionPerformed

    private void btn_ClearAllItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearAllItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClearAllItemsActionPerformed

    private void btn_cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cokeActionPerformed
        // TODO add your handling code here:
        /**
         * This is how you display an item and price from the
         * database into a DefaultTableModel
         */       
        DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
                        // Item and price
        Object[] row = {menu[6][0], menu[6][1]};
        model.addRow(row);
    }//GEN-LAST:event_btn_cokeActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:

        if (dbconn.isEmployee(Integer.parseInt(txt_empId.getText()))) {

            lbl_nameOfEmpLoggedIn.setText(dbconn.Login(Integer.parseInt(txt_empId.getText())));
            Panel_ParentCard.removeAll();
            Panel_ParentCard.add(Card_ClockinClockOut);
            Panel_ParentCard.repaint();
            Panel_ParentCard.revalidate();
        } else {
            JOptionPane.showMessageDialog(Card_EmpLogin, "Login Failed");
        }


    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_ClockInClockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClockInClockOutActionPerformed
        // TODO add your handling code here:
        tCard.setDate();

        dbconn.Clockin(Integer.parseInt(txt_empId.getText()), tCard.getDate().toString());
        System.out.println(txt_empId.getText() + "\n");
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Menu);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_ClockInClockOutActionPerformed

    private void btn_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManagerActionPerformed
        // TODO add your handling code here:
        Panel_ParentCard.removeAll();
        Panel_ParentCard.add(Card_Manager);
        Panel_ParentCard.repaint();
        Panel_ParentCard.revalidate();
    }//GEN-LAST:event_btn_ManagerActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
                        // Item and price
        Object[] row = {menu[7][0], menu[7][1]};
        model.addRow(row);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card_ClockinClockOut;
    private javax.swing.JPanel Card_EmpLogin;
    private javax.swing.JPanel Card_Manager;
    private javax.swing.JPanel Card_Menu;
    private javax.swing.JPanel Card_OrderPerTable;
    private javax.swing.JPanel Card_POS;
    private javax.swing.JPanel Card_POSTable;
    private javax.swing.JPanel Card_TimeCard;
    private javax.swing.JPanel Panel_Appetizers;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Category;
    private javax.swing.JPanel Panel_Drinks;
    private javax.swing.JPanel Panel_ParentCard;
    private javax.swing.JPanel Panel_ParentMenu;
    private javax.swing.JPanel Panel_PaymentButtons;
    private javax.swing.JPanel Panel_TopButtons;
    private javax.swing.JButton btn_Appetizers;
    private javax.swing.JButton btn_Burgers;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_ClearAllItems;
    private javax.swing.JButton btn_ClockInClockOut;
    private javax.swing.JButton btn_Desserts;
    private javax.swing.JButton btn_Drinks;
    private javax.swing.JButton btn_Extras;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_Manager;
    private javax.swing.JButton btn_POS;
    private javax.swing.JButton btn_Pay;
    private javax.swing.JButton btn_PrintBill;
    private javax.swing.JButton btn_Salads;
    private javax.swing.JButton btn_SaveBill;
    private javax.swing.JButton btn_TimeCard;
    private javax.swing.JButton btn_VoidItem;
    private javax.swing.JButton btn_Wings;
    private javax.swing.JButton btn_coke;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_EmpLogin;
    private javax.swing.JLabel lbl_LoggedInAs;
    private javax.swing.JLabel lbl_nameOfEmpLoggedIn;
    private javax.swing.JScrollPane scr_Burgers;
    private javax.swing.JScrollPane scr_Desserts;
    private javax.swing.JScrollPane scr_Extras;
    private javax.swing.JScrollPane scr_Salad;
    private javax.swing.JScrollPane scr_Wings;
    private javax.swing.JTable tbl_order;
    private javax.swing.JTextField txt_empId;
    // End of variables declaration//GEN-END:variables
}
